services:
  - type: web
    name: task3-user-login
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: userlogin-db
          property: connectionString

databases:
  - name: userlogin-db
